version: '3.8'
services:
  hl-model-api:
    build: .
    image: hl-model-api:latest
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      PYTHONDONTWRITEBYTECODE: '1'
      PYTHONUNBUFFERED: '1'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
